/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testAppExists () {
    try {
      Class.forName("my.app.App");
    } catch (ClassNotFoundException e) {
      fail("Should have a class named App.");
    }
  }
}